# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9pDk6ssPnayJ4xNXsTvDu6pWJCU8tI8

# ***RESUME CREATOR***
"""

!pip install -q google-generativeai pdfplumber

import google.generativeai as genai
import json
import re
import pdfplumber
import time

from google.colab import userdata, files
from typing import TypedDict, List, Optional
genai.configure(api_key=userdata.get('Gemini-API-Key'))

from tenacity import retry, wait_exponential, stop_after_attempt, retry_if_exception_type
from google.api_core import exceptions

import logging
logging.getLogger('tornado.access').setLevel(logging.CRITICAL)

import pkg_resources
print(pkg_resources.get_distribution('google-generativeai').version)

import google.generativeai as genai
import json
import re
import pdfplumber
import time
import logging

from google.colab import userdata, files
from typing import TypedDict, List, Optional
from tenacity import retry, wait_exponential, stop_after_attempt, retry_if_exception_type
from google.api_core import exceptions

# Configure API Key
genai.configure(api_key=userdata.get('Gemini-API-Key'))

# Configure model
model = genai.GenerativeModel("gemini-2.5-flash-lite")

# Suppress tornado access logs
logging.getLogger('tornado.access').setLevel(logging.CRITICAL)


# =========================================================
# SCHEMA
# =========================================================

class Education(TypedDict):
    degree: Optional[str]
    institute: Optional[str]
    year: Optional[str]
    score: Optional[str]


class Experience(TypedDict):
    company: Optional[str]
    role: Optional[str]
    duration: Optional[str]
    highlights: List[str]


class Project(TypedDict):
    name: Optional[str]
    description: Optional[str]
    tech_stack: List[str]


class Resume(TypedDict):
    name: Optional[str]
    email: Optional[str]
    phone: Optional[str]
    linkedin_url: Optional[str]
    education: List[Education]
    skills: List[str]
    experience: List[Experience]
    projects: List[Project]
    total_experience_years: float
    summary: Optional[str]


# =========================================================
# PROMPT
# =========================================================

PROMPT = """
Extract resume data.

Rules:
1. Return valid JSON only
2. Use null for missing fields
3. Do not invent values
4. Normalize phone to +91XXXXXXXXXX
5. Skills must be clean and unique
6. Summary must be one sentence
"""


# =========================================================
# HELPER FUNCTIONS
# =========================================================

def clean_json(text):

    text = (
        text
        .replace("```json", "")
        .replace("```", "")
        .strip()
    )

    return json.loads(text)


def validate(data):

    # Email validation
    email = data.get("email")

    if email and "@" not in email:
        data["email"] = None

    # Phone normalization
    phone = data.get("phone")

    if phone:

        digits = re.sub(r"\\D", "", phone)

        if len(digits) == 10:
            data["phone"] = f"+91{digits}"

    # Experience validation
    exp = data.get("total_experience_years")

    if exp is not None and exp < 0:
        data["total_experience_years"] = 0.0

    return data


@retry(
    wait=wait_exponential(multiplier=1, min=4, max=60),
    stop=stop_after_attempt(15), # Increased retry attempts
    retry=retry_if_exception_type(exceptions.TooManyRequests)
)
def generate_content_with_retry(prompt_text, generation_config):
    return model.generate_content(prompt_text, generation_config=generation_config)


# =========================================================
# WAY 1 — PROMPT ONLY
# =========================================================

def parse_prompt(text):

    generation_config={
        "temperature": 0.2,
        "max_output_tokens": 2048
    }

    response = generate_content_with_retry(
        f"{PROMPT}\\n\\n{text}",
        generation_config=generation_config
    )

    return validate(
        clean_json(response.text)
    )


# =========================================================
# WAY 2 — MIME TYPE
# =========================================================

def parse_mime(text):

    generation_config={
        "temperature": 0.2,
        "max_output_tokens": 2048,
        "response_mime_type": "application/json"
    }

    response = generate_content_with_retry(
        f"{PROMPT}\\n\\n{text}",
        generation_config=generation_config
    )

    return validate(
        clean_json(response.text)
    )


# =========================================================
# WAY 3 — SCHEMA
# =========================================================

def parse_schema(text):

    generation_config={
        "temperature": 0.2,
        "max_output_tokens": 2048,
        "response_mime_type": "application/json",
        "response_schema": Resume
    }

    response = generate_content_with_retry(
        f"{PROMPT}\\n\\n{text}",
        generation_config=generation_config
    )

    return validate(
        clean_json(response.text)
    )


# =========================================================
# DISPLAY FUNCTION
# =========================================================

def show(title, data):

    print(f"\\n{'='*20} {title} {'='*20}")

    print(
        json.dumps(
            data,
            indent=2,
            ensure_ascii=False
        )
    )

    print("\\nSUMMARY")

    print(
        f"Name: {data.get('name')} | "
        f"Email: {data.get('email')} | "
        f"Phone: {data.get('phone')}"
    )

    print(
        "Top Skills:",
        ", ".join(data.get("skills", [])[:5])
    )

    print(
        "Experience:",
        data.get("total_experience_years"),
        "years"
    )


# =========================================================
# TEST RESUME 1
# =========================================================

resume1 = """
ANJALI SHARMA
Email: anjali.sharma@gmail.com | Phone: 9876543210
LinkedIn: linkedin.com/in/anjali-sharma

EDUCATION
- B.Tech in Computer Science, IIT Delhi, 2024 (CGPA: 8.9)

SKILLS
Python, Django, FastAPI, React.js, MongoDB

EXPERIENCE
Software Engineering Intern, Flipkart

PROJECTS
- AgriBot chatbot using Gemini API
"""


# =========================================================
# TEST RESUME 2
# =========================================================

resume2 = """
hii i am ravi (ravi.k@yahoo.in / 8765-432-100)

btech from vit vellore 2023

skills:
java, python, react

internship at zoho

project:
NoteShare app using firebase
"""


# =========================================================
# TEST 1 OUTPUT
# =========================================================

print("\\n############ TEST RESUME 1 ############")

show(
    "WAY 1 - PROMPT",
    parse_prompt(resume1)
)

show(
    "WAY 2 - MIME",
    parse_mime(resume1)
)

show(
    "WAY 3 - SCHEMA",
    parse_schema(resume1)
)


# =========================================================
# TEST 2 OUTPUT
# =========================================================

print("\\n############ TEST RESUME 2 ############")

show(
    "WAY 1 - PROMPT",
    parse_prompt(resume2)
)

show(
    "WAY 2 - MIME",
    parse_mime(resume2)
)

show(
    "WAY 3 - SCHEMA",
    parse_schema(resume2)
)


# =========================================================
# TEST 3 — PDF RESUME
# =========================================================

print("\\nUPLOAD PDF RESUME")

uploaded = files.upload()

pdf_file = list(uploaded.keys())[0]


# =========================================================
# PDF TEXT EXTRACTION
# =========================================================

def extract_text_from_pdf(path):

    text = ""

    with pdfplumber.open(path) as pdf:

        for page in pdf.pages:

            page_text = page.extract_text()

            if page_text:
                text += page_text + "\\n"

    return text


resume_text = extract_text_from_pdf(pdf_file)

print("\\nEXTRACTED TEXT:\\n")
print(resume_text)


# =========================================================
# PDF PARSING OUTPUT
# =========================================================

print("\\n############ PDF RESUME OUTPUT ############")

show(
    "WAY 1 - PROMPT",
    parse_prompt(resume_text)
)

show(
    "WAY 2 - MIME",
    parse_mime(resume_text)
)

show(
    "WAY 3 - SCHEMA",
    parse_schema(resume_text)
)